version: '2'
services:
  hapi:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3003:3003"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3003
  