version: '2'
services:
  loopback:
    build:
      context: loopback/.
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/loopback:/app
    environment:
      - PORT=3000
  restify:
    build:
      context: restify/.
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ${PWD}/restify:/app
    environment:
      - PORT=3001
