version: '2'
services:
  koa:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3005:3005"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3005
