version: '2'
services:
  actionhero:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3002:3002"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3002
