version: '2'
services:
  socket_io:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3004:3004"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3004
