version: '2'
services:
  restify:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3001:3001"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3001
