version: '2'
services:
  loopback:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}:/app
    environment:
      - PORT=3000